version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4007:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/typingapp
      - JWT_SECRET=dev_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: